### ISSUE TITLE
Question: Which extension should I use for Sketch scripts?

### ISSUE THREAD

**Issue by guerrero** [BohemianCoding/ExampleSketchPlugins#2]
From Bohemian Coding docs:
>Bundles contain a manifest.json file, one or more **`.sketchscript`** files (containing scripts written in CocoaScript or JavaScript) which implement commands shown in the Plugins menu, and any number of shared library scripts and resource files.

But in this repo you're using `.cocoaScript` extension. Is there any reason to use one in particular?

**Comment by bomberstudios** [comment]
That's a typo on our side, I'll fix it : )

(The truth is you can use any extension you want for your code, but we thought it'd make sense to have a specific extension for your CocoaScript files)

**Comment by guerrero** [comment]
Great. Thanks!

**Comment by samdeane** [comment]
We were talking about changing things at some point so that the `.cocoascript` files are treated a bit differently from `.js` files. For example, if you use the cocoa syntax, that might not work in future if the file extension isn't `.cocoascript`.

So for the sake of future-proofing, I'd recommend `.cocoascript` for now.

**Comment by guerrero** [comment]
Thanks for the explanation Sam
